#!/usr/bin/env node

const bcrypt = require('bcrypt')

if (process.argv.length < 3) {
  console.log('not enough argument')
  process.exit()
}

const raw = process.argv[2]

const salt = bcrypt.genSaltSync(10)
console.log(bcrypt.hashSync(raw, salt))
